[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "node_modules"]
test = "test"
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200

[profile.ci]
fs_permissions = [{ access = "read", path = "./" }]

